[project]
name = "pycontainers"
version = "2.0.0"
description = "Python wrapper for docker/container/podman cli"
authors = [{name = "Sylvain Mouquet", email = "sylvain.mouquet@gmail.com"}]
readme = "README.md"
requires-python = ">=3.14"
dependencies = [
    "asgi-lifespan>=2.1.0",
    "proxycraft",
    "nest-asyncio>=1.6.0"
]

license = { text = "MIT" }
url = "https://github.com/sylvainmouquet/pycontainer"
keywords = [
    "docker",
    "python",
    "wrapper",
    "podman",
    "container"
]
classifiers = [
    "Development Status :: 5 - Production/Stable",
    "Framework :: Pytest",
    "Intended Audience :: Developers",
    "License :: OSI Approved :: MIT License",
    "Programming Language :: Python",
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3.14",
    "Topic :: Software Development :: Libraries :: Python Modules"
]

[project.urls]
homepage = "https://github.com/sylvainmouquer/pycontainers"
documentation = "https://github.com/sylvainmouquer/pycontainers"
repository = "https://github.com/sylvainmouquer/pycontainers"
changelog = "https://github.com/sylvainmouquer/pycontainers/releases"


[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[dependency-groups]
dev = [
    "certifi>=2026.1.4",
    "httpx>=0.28.1",
    "pip>=24.2",
    "pyright>=1.1.390",
    "pytest-asyncio>=0.24.0",
    "pytest-cov>=6.0.0",
    "pytest-mock>=3.14.0",
    "pytest>=8.3.3",
    "ruff>=0.6.7",
    "dotenv>=0.9.9",
]

[tool.uv.sources]
pycontainers = { path = "pycontainers" }
proxycraft = { path = "../proxycraft", editable = true }

[project.entry-points.pytest11]
pycontainers = "pycontainers"

[tool.pytest.ini_options]
testpaths = ["tests"]

[tool.coverage.run]
source = ["pycontainers"]
branch = false

[tool.coverage.report]
show_missing = true
skip_covered = false
exclude_lines = [
    "pragma: no cover",
    "if TYPE_CHECKING:",
    "raise NotImplementedError",
]
